homeRegion: &HOME_REGION us-east-1
enabledRegions:
  - *HOME_REGION
  - us-west-2

managementAccountAccessRole: AWSControlTowerExecution

cloudwatchLogRetentionInDays: 3653

sessionManager:
  sendToCloudWatchLogs: false
  sendToS3: true
  region: *HOME_REGION
  lifecycleRules: []

accessLogBucket:
  importedBucket:
    name: aws-accelerator-central-logs-bucket
  lifecycleRules: []

centralLogsBucket:
  importedBucket:
    name: aws-accelerator-central-logs-bucket
  lifecycleRules: []

elbLogBucket:
  importedBucket:
    name: aws-accelerator-elb-access-logs-bucket
  lifecycleRules: []

reports:
  costAndUsageReport:
    compression: GZIP
    format: textORcsv
    reportName: accelerator-cur
    s3Prefix: cur
    timeUnit: DAILY
    refreshClosedReports: true
    reportVersioning: CREATE_NEW_REPORT
  budgets:
    - name: AcceleratorBudget
      timeUnit: MONTHLY
      type: COST
      amount: 1000
      includeUpfront: true
      includeTax: true
      includeSupport: true
      includeSubscription: true
      includeRecurring: true
      includeOtherSubscription: true
      includeDiscount: true
      includeCredit: false
      refreshClosedReports: true
      useBlended: false
      useAmortized: false
      unit: USD
      notifications:
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 90
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: budget-notifications@example.com

backup:
  vaults:
    - name: BackupVault
      deploymentTargets:
        organizationalUnits:
          - Root

ssmAutomation:
  documentSets: []

tags:
  - key: Environment
    value: Production
  - key: Project
    value: LandingZone
