enable: true
organizationAdminAccount: Audit

organizationalUnits:
  - name: PCS
    accounts:
      - LogArchive
      - Audit
  - name: Infrastructure
    accounts:
      - Network
      - Services
    organizationalUnits:
      - name: Tnt0
        accounts:
          - Infrastructure-Tnt0
      - name: Tnt3
        accounts:
          - Infrastructure-Tnt3
      - name: Tnt4
        accounts:
          - Infrastructure-Tnt4

quarantineNewAccounts:
  enable: true
  scpPolicyName: Quarantine

serviceControlPolicies:
  - name: AcceleratorGuardrails1
    description: Accelerator Guardrails 1
    policy: organization-config-policies/AcceleratorGuardrails1.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Root
  - name: AcceleratorGuardrails2
    description: Accelerator Guardrails 2
    policy: organization-config-policies/AcceleratorGuardrails2.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Infrastructure
  - name: Quarantine
    description: Quarantine policy for new accounts
    policy: organization-config-policies/Quarantine.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: []

taggingPolicies:
  - name: TaggingPolicy
    description: Organization tagging policy
    policy: organization-config-policies/TaggingPolicy.json
    deploymentTargets:
      organizationalUnits:
        - Root

backupPolicies:
  - name: BackupPolicy
    description: Organization backup policy
    policy: organization-config-policies/BackupPolicy.json
    deploymentTargets:
      organizationalUnits:
        - Root

accountWarmingEnabled: false

delegatedAdminAccount:
  account: Audit
  services:
    - access-analyzer.amazonaws.com
    - cloudtrail.amazonaws.com
    - config.amazonaws.com
    - detective.amazonaws.com
    - fms.amazonaws.com
    - guardduty.amazonaws.com
    - inspector2.amazonaws.com
    - macie.amazonaws.com
    - securityhub.amazonaws.com
    - ssm.amazonaws.com
    - sso.amazonaws.com
    - storage-lens.s3.amazonaws.com

enablePolicyTypesInControlTower:
  - SERVICE_CONTROL_POLICY
  - TAG_POLICY
  - BACKUP_POLICY
