homeRegion: us-east-1
enabledRegions:
  - us-east-1
  - us-west-2
  - eu-west-1

mandatoryAccounts:
  - name: Management
    email: atos-pcs-aws-management@pcsfinops.aws.atos.net
    organizationalUnit: Root
  - name: Audit
    email: atos-pcs-aws-audit@pcsfinops.aws.atos.net
    organizationalUnit: Root
  - name: LogArchive
    email: atos-pcs-aws-logarchive@pcsfinops.aws.atos.net
    organizationalUnit: Root

workloadAccounts:
  - name: Services
    email: atos-pcs-aws-services@pcsfinops.aws.atos.net
    organizationalUnit: PCS
  - name: Production
    email: atos-pcs-aws-production@pcsfinops.aws.atos.net
    organizationalUnit: PCS
  - name: Development
    email: atos-pcs-aws-development@pcsfinops.aws.atos.net
    organizationalUnit: PCS
  - name: Test
    email: atos-pcs-aws-development@pcsfinops.aws.atos.net
    organizationalUnit: PCS

accountWarmup:
  enable: true
  concurrentRequests: 5

controlTower:
  enable: true
  landingZone:
    version: "3.3"
    logging:
      account: LogArchive
      centralizedLoggingRegion: us-east-1
    security:
      account: Audit
  controls:
    - AWS-GR_AUDIT_BUCKET_PUBLIC_READ_PROHIBITED
    - AWS-GR_CLOUDTRAIL_ENABLED
    - AWS-GR_CONFIG_ENABLED
